#!/usr/bin/env python3
"""Layout-hash tool for the REKS catalog BLOB ABI over reks_layout.json,
shared by the C++ build (--header emits REKS_LAYOUT_HASH, REKS_COEFF_BITS,
REKS_FON_N_BITS, REKS_FON_OFF_BITS) and the Python .bin generator
(layout_hash()), so both stamp the same hash.

Strips comment keys (leading '_') at every nesting level, then hashes
everything left in reks_layout.json.
"""
import hashlib
import json
import struct
import sys


def _strip_comments(obj):
    if isinstance(obj, dict):
        return {k: _strip_comments(v) for k, v in obj.items() if not k.startswith("_")}
    if isinstance(obj, list):
        return [_strip_comments(v) for v in obj]
    return obj


def layout_hash(json_path) -> int:
    spec = _strip_comments(json.loads(open(json_path).read()))
    canon = json.dumps(spec, sort_keys=True, separators=(",", ":")).encode()
    return struct.unpack("<Q", hashlib.sha256(canon).digest()[:8])[0]


def emit_header(json_path, out_path) -> int:
    spec = json.loads(open(json_path).read())
    h = layout_hash(json_path)
    meta = spec["value_meta"]
    text = ("#pragma once\n"
            "// AUTO-GENERATED by gen_layout_hash.py from reks_layout.json -- DO NOT EDIT.\n"
            "#include <cstdint>\n"
            f"constexpr uint64_t REKS_LAYOUT_HASH = 0x{h:016x}ULL;\n"
            "// Bit widths a value record packs its coefficient id, FON window length and\n"
            "// window start in. Emitted rather than mirrored in C++: a struct-size drift trips\n"
            "// a static_assert, a field-width drift decodes silently into wrong numbers.\n"
            f"constexpr int REKS_COEFF_BITS = {meta['coeff_bits']};\n"
            f"constexpr int REKS_FON_N_BITS = {meta['fon_n_bits']};\n"
            f"constexpr int REKS_FON_OFF_BITS = {meta['fon_off_bits']};\n")
    open(out_path, "w").write(text)
    return h


def main(argv):
    if len(argv) == 4 and argv[1] == "--header":
        h = emit_header(argv[2], argv[3])
        print(f"wrote {argv[3]} : REKS_LAYOUT_HASH = 0x{h:016x}")
    elif len(argv) == 2:
        print(f"0x{layout_hash(argv[1]):016x}")
    else:
        print("usage: gen_layout_hash.py [--header <reks_layout.json> <out.h>] | <reks_layout.json>", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
